services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./server/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    container_name: exams-db

  server: &server
    build: .
    command: bash -c 'bundle install && ruby server.rb'
    volumes:
      - ./server:/app
      - bundle_data_server:/usr/local/bundle
      - temp_data:/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - REDIS_URL=redis://redis:6379/0
    container_name: exams-server

  app:
    build: ./app
    command: bash -c 'bundle install && ruby app.rb'
    volumes:
      - ./app:/app
      - bundle_data_app:/usr/local/bundle
    ports:
      - "4000:4000"
    depends_on:
      - server
    container_name: exams-app

  sidekiq:
    <<: *server
    container_name: exams-sidekiq
    ports: []
    command: bash -c 'bundle install && sidekiq -r ./jobs/import_job.rb'
    depends_on:
      - redis

  redis:
    image: redis

volumes:
  bundle_data_server:
  bundle_data_app:
  temp_data: