services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./server/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    container_name: relabs-db

  server:
    build: .
    command: bash -c 'bundle install && ruby server.rb'
    volumes:
      - ./server:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://my_user:my_password@db:5432/my_database
    container_name: relabs-server

volumes:
  bundle_data: